# Generated by Django 4.2.3 on 2023-07-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
