# Generated by Django 4.2.3 on 2023-07-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareasApp', '0002_tarea_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
            },
        ),
    ]
