# Generated by Django 4.2.3 on 2023-07-08 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareasApp', '0003_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tareasApp.prioridad'),
        ),
    ]
